name: dsw2025-dokploy-uhwhf9

services:
  postgres:
    container_name: keycloak-postgres  # Nombre único
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB_KC}
      POSTGRES_USER: ${POSTGRES_USER_KC}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_KC}
    networks:
      dokploy-network:
        aliases:
          - keycloak-postgres  # Alias único en la red
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER_KC}"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    command: start --import-realm
    environment:
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HOSTNAME_ADMIN_URL: ${KC_HOSTNAME_ADMIN_URL}
      KC_PROXY: ${KC_PROXY:-edge}
      KC_PROXY_ADDRESS_FORWARDING: ${KC_PROXY_ADDRESS_FORWARDING:-true}
      QUARKUS_HTTP_PROXY_ADDRESS_FORWARDING: ${QUARKUS_HTTP_PROXY_ADDRESS_FORWARDING:-true}
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/${POSTGRES_DB_KC}  # Usa el alias específico
      KC_DB_USERNAME: ${POSTGRES_USER_KC}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD_KC}
    ports:
      - 8080:8080
    volumes:
      - ./realm-config:/opt/keycloak/data/import
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dokploy-network
    labels:
      - traefik.docker.network=dokploy-network
      - traefik.http.routers.dsw2025-dokploy-uhwhf9-5-web.rule=Host(`keycloak.mmalgor.com.ar`)
      - traefik.http.routers.dsw2025-dokploy-uhwhf9-5-web.entrypoints=web
      - traefik.http.services.dsw2025-dokploy-uhwhf9-5-web.loadbalancer.server.port=8080
      - traefik.http.routers.dsw2025-dokploy-uhwhf9-5-web.service=dsw2025-dokploy-uhwhf9-5-web
      - traefik.http.routers.dsw2025-dokploy-uhwhf9-5-web.middlewares=redirect-to-https@file
      - traefik.http.routers.dsw2025-dokploy-uhwhf9-5-websecure.rule=Host(`keycloak.mmalgor.com.ar`)
      - traefik.http.routers.dsw2025-dokploy-uhwhf9-5-websecure.entrypoints=websecure
      - traefik.http.services.dsw2025-dokploy-uhwhf9-5-websecure.loadbalancer.server.port=8080
      - traefik.http.routers.dsw2025-dokploy-uhwhf9-5-websecure.service=dsw2025-dokploy-uhwhf9-5-websecure
      - traefik.http.routers.dsw2025-dokploy-uhwhf9-5-websecure.tls.certresolver=letsencrypt
      - traefik.enable=true

volumes:
  postgres_data:
    driver: local

networks:
  dokploy-network:
    external: true
